### ISSUE TITLE
Confirm dialog

### ISSUE THREAD

**Issue by austinv11** [greyli/flask-dropzone#15]
Hello, not sure if this is the right place to ask but, is it possible to implement a dynamic confirm dialog on uploads? So that, for example, I could implement a serverside check which may fail an upload but then add a way to allow someone with admin privileges to "override" the serverside check and force an upload.

**Comment by greyli** [comment]
I do not quite understand what you mean, but this (confirm dialog) need to implement by yourself. If you look for return validation message from the server side after server check, you can give a look at [this section in doc](https://github.com/greyli/flask-dropzone#server-side-validation).

**Comment by austinv11** [comment]
What I mean, is that I want to do server-side validation, and if it fails, I'd like a way to override the validation if the user has a certain permission on the backend.

**Comment by greyli** [comment]
So, why you need a confirm dialog?

**Comment by austinv11** [comment]
Because we have stringent checks on files being uploaded and we want to be able to override it in the case that the checks are wrong and the user has admin privileges.

**Comment by greyli** [comment]
I think maybe you should use Dropzone.js directly for better flexibility since Flask-Dropzone only suits simple use cases currently.

**Comment by greyli** [comment]
I'll close this issue for now. Please feel free to comment further or re-open this issue if you wish.
