### ISSUE TITLE
complete-redirect error.

### ISSUE THREAD

**Issue by JangHanbin** [greyli/flask-dropzone#18]
I think, there is an logical error.

complete page should be called when after file totally uploaded. but example code not.

even file filtered by app.config still called completed page.

did I wrong??

**Comment by greyli** [comment]
Sorry for the late response. I tested the example application, but can't reprocude your issue. Can you provide the minimal application to reproduce your problem?

**Comment by greyli** [comment]
Closing for inactive, please feel free to comment or reopen.
