### ISSUE TITLE
手机上选择相册里的照片时不能选择多张

### ISSUE THREAD

**Issue by sjwhi8989** [greyli/flask-dropzone#19]
手机上选择相册里的照片时不能选择多张，只能选择一张确定后再选择一张，怎么样才能像微信和QQ那样可以一起选择多张要上传的照片。
谢谢。

**Comment by greyli** [comment]
关于 Dropzonejs 本身的问题，请到 https://github.com/enyo/dropzone 反馈。顺便在 Android + Chrome 上测试了一下，按住文件可以多选。
