### ISSUE TITLE
How to remove local file when remove file button was pressed?

### ISSUE THREAD

**Issue by Sacchid** [greyli/flask-dropzone#20]
From [flask-dropzone/examples/custom-option][1], whenever remove button is pressed, image (file) is removed from web-view but **not from uploads folder**.
How to check which image is removed by clicking on ![image](https://user-images.githubusercontent.com/22224760/54116556-062b1700-4415-11e9-9a5e-d5c37a043529.png) button & how to remove it from _uploads_?
And can I temp. save files for session & then based some logic decide to delete them or save permanently.

[1]: https://github.com/greyli/flask-dropzone/blob/master/examples/custom-options/templates/index.html "custom option from example"

**Comment by greyli** [comment]
Sorry for taking so long. This feature is not implemented currently, but your can make it by yourself. First, register the event listeners with JavaScript:
```js
Dropzone.options.myAwesomeDropzone = {
    success: function(file, response) {
        file.serverFileName = response.file_name;  // pass filename
    },
    removedfile: function (file, data) {  // triggered when remove file button was clicked
        $.ajax({  // send AJAX request to Flask to remove file
            type:'POST',
            url:'/deletefile',
            data : {"filename" : file.serverFileName},  // pass filename
            success : function (data) {
                alert('File removed from server.')
            }
        });
    }
};
```
Then, create the view function to delete file with Flask:
```py
@app.route('/deletefile')
def delete_file():
    filename = request.form['filename']
    file_path = os.path.join(your_upload_path, filename)
    os.remove(file_path)
```
Not test yet, let me know if it works ;)

**Comment by greyli** [comment]
Closing for inactive, please feel free to comment or reopen.

**Comment by A-Shot** [comment]
here is my code can any one let me know what Im doing wrong ?
" success: function(file, response) {" not working at all.


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Flask-Dropzone Demo: Custom Options</title>
  {{ dropzone.load_css() }}
  {{ dropzone.style('border: 2px dashed #0087F7; margin: 10%; min-height: 400px;') }}
</head>
<body>
  {{ dropzone.create(action='upload') }}
  <button id="upload-btn">Upload</button>
  {{ dropzone.load_js() }}
  {{ dropzone.config(custom_init='dz = this;document.getElementById("upload-btn").addEventListener("click", function handler(e) {dz.processQueue();});',
                     custom_options='autoProcessQueue: false, addRemoveLinks: true, parallelUploads: 20,') }}





<script type="text/javascript">
$(document).ready(function () {

    alert("success 1");
    console.log("3");

Dropzone.options.myAwesomeDropzone = {
  
    success: function(file, response) {
       console.log("5");
        file.serverFileName = response.file_name;  // pass filename

    },
    removedfile: function (file, data) {  // triggered when remove file button was clicked
        $.ajax({  // send AJAX request to Flask to remove file
            type:'POST',
            url:'/deletefile',
            data : {"filename" : file.serverFileName},  // pass filename
            success : function (data) {
                alert('File removed from server.')
            }
          });
         }
       };
   });
</script>


</body>
</html>

**Comment by A-Shot** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Flask-Dropzone Demo: Custom Options</title>
  {{ dropzone.load_css() }}
  {{ dropzone.style('border: 2px dashed #0087F7; margin: 10%; min-height: 400px;') }}
</head>
<body>
  {{ dropzone.create(action='upload') }}
  <button id="upload-btn">Upload</button>
  {{ dropzone.load_js() }}
  {{ dropzone.config(custom_init='dz = this;document.getElementById("upload-btn").addEventListener("click", function handler(e) {dz.processQueue();});',
                     custom_options='autoProcessQueue: false, addRemoveLinks: true, parallelUploads: 20,') }}





<script type="text/javascript">
$(document).ready(function () {

    alert("success 1");
    console.log("3");

Dropzone.options.myAwesomeDropzone = {
  
    success: function(file, response) {
       console.log("5");
        file.serverFileName = response.file_name;  // pass filename

    },
    removedfile: function (file, data) {  // triggered when remove file button was clicked
        $.ajax({  // send AJAX request to Flask to remove file
            type:'POST',
            url:'/deletefile',
            data : {"filename" : file.serverFileName},  // pass filename
            success : function (data) {
                alert('File removed from server.')
            }
          });
         }
       };
   });
</script>


</body>
</html>

**Comment by A-Shot** [comment]
### here is my code can any one let me know what I'm doing wrong?

- <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Flask-Dropzone Demo: Custom Options</title>
  {{ dropzone.load_css() }}
  {{ dropzone.style('border: 2px dashed #0087F7; margin: 10%; min-height: 400px;') }}
</head>
<body>
  {{ dropzone.create(action='upload') }}
  <button id="upload-btn">Upload</button>
  {{ dropzone.load_js() }}
  {{ dropzone.config(custom_init='dz = this;document.getElementById("upload-btn").addEventListener("click", function handler(e) {dz.processQueue();});',
                     custom_options='autoProcessQueue: false, addRemoveLinks: true, parallelUploads: 20,') }}





<script type="text/javascript">
$(document).ready(function () {

    alert("success 1");
    console.log("3");

Dropzone.options.myAwesomeDropzone = {
  
    success: function(file, response) {
       console.log("5");
        file.serverFileName = response.file_name;  // pass filename

    },
    removedfile: function (file, data) {  // triggered when remove file button was clicked
        $.ajax({  // send AJAX request to Flask to remove file
            type:'POST',
            url:'/deletefile',
            data : {"filename" : file.serverFileName},  // pass filename
            success : function (data) {
                alert('File removed from server.')
            }
          });
         }
       };
   });
</script>


</body>
</html>

**Comment by CFGrote** [comment]
i'm interested in this feature, too. any updates? where exactly am i supposed to paste the js snipped (copied from above)?

```
Dropzone.options.myAwesomeDropzone = {
    success: function(file, response) {
        file.serverFileName = response.file_name;  // pass filename
    },
    removedfile: function (file, data) {  // triggered when remove file button was clicked
        $.ajax({  // send AJAX request to Flask to remove file
            type:'POST',
            url:'/deletefile',
            data : {"filename" : file.serverFileName},  // pass filename
            success : function (data) {
                alert('File removed from server.')
            }
        });
    }
};
```
