### ISSUE TITLE
redirect_view resolving url

### ISSUE THREAD

**Issue by volzon** [greyli/flask-dropzone#22]
DROPZONE_REDIRECT_VIEW (redirect_view) use url_for() to resolve the url, but i can not find any way to pass arguments. There is also no way of passing an url.

Suggestion1: use get_url() from utils.py so that its possible to pass complete url or for example '/index/2' this is OK as a quick fix. Must do it both at line 67 and 203

Suggestion2:
Fix/Clarify in the docs how to pass arguments with DROPZONE_REDIRECT_VIEW

**Comment by SoulMUSZE** [comment]
Is there a fix that can be used right now to pass arguments to the redirect view?

**Comment by greyli** [comment]
You can pass redirect URL directly in template with `redirect_url` keyword:
```jinja
{{ dropzone.config(redirect_url=url_for('endpoint', foo=bar)) }}
```

**Comment by SoulMUSZE** [comment]
Thanks so much!
