### ISSUE TITLE
compete redirect. can't access to POST request in redirection view

### ISSUE THREAD

**Issue by vedmed85** [greyli/flask-dropzone#24]
```
@app.route('/completed')
def completed():
    return '<h1>The Redirected Page</h1><p>Upload completed.</p>'
```

Now this code  work, but there no way to show image count, render image previews etc. Would be perfect if post request will be redirected to this view.

```
@app.route('/completed'', methods=['POST', 'GET'])
def upload():
     if request.method == 'POST':
             .....
     return '<h1>The Redirected Page</h1><p>Upload completed.</p>'
```

**Comment by greyli** [comment]
IMO, complete redirection meant to bring the user to a new page when uploading complete, so it's not reasonable to use POST here.

**Comment by greyli** [comment]
I'll close this issue for now. Please feel free to comment further or re-open this issue if you wish.
