### ISSUE TITLE
Issues with CSRF 

### ISSUE THREAD

**Issue by ar-anvd** [greyli/flask-dropzone#27]
Hello,

Using the current setup of the [docs](https://flask-dropzone.readthedocs.io/en/latest/advanced.html#csrf-protect), the csrf protection will apply to the every form and every post of the app, this config ideally should apply only to the upload of dropzone, not the entire app.

**Comment by greyli** [comment]
Hi, you will need to handle this by yourself since the extension CSRFProtect default to enable CSRF check for all POST requests. The solution will be like this:

```python
from flask import request

app.config['WTF_CSRF_CHECK_DEFAULT'] = False  # disable all check

@app.before_request
def check_csrf():
    if request.endpoint == 'upload':  # only protect your upload endpoint
        csrf.protect()
```
Find more info on it's [docs](https://flask-wtf.readthedocs.io/en/latest/csrf.html#exclude-views-from-protection).
