### ISSUE TITLE
Send multiple files in one request

### ISSUE THREAD

**Issue by AnastasiaLd** [greyli/flask-dropzone#3]
I have set in my config file DROPZONE_MAX_FILES=3 and DROPZONE_PARALLEL_UPLOADS = 3 expecting all the files uploaded would be handles in one POST request, however each time i drop a file in the dropzone all files are being received but in different requests. 
What i would like to achieve without having to save the files somewhere is to get a list of all files uploaded [file1, file2, file3] so i can later use them in a pandas method that can read and combine all files in one dataframe but at the moment the result i am getting with request.getlist() is a list containing one file per request like this: [file1] [file2] [file3].

Is there anyway to do this?

On a side note i am also a little bit confused about the DROPZONE_REDIRECT_VIEW option since is not working for me.  Ex. {{ url_for('records.allrecords') }} is my view but DROPZONE_REDIRECT_VIEW = 'records.allrecors' doesn't work.

I would really appreciate an input on this. Thank you.

**Comment by greyli** [comment]
These features were added to version 1.4.1. Do you update Flask-Dropzone? 

As the Q1, you also need to set `DROPZONE_UPLOAD_MULTIPLE` as True to enable multiple uploads.

**Comment by AnastasiaLd** [comment]
Hi thank you for your reply. I missed typed my question i ment to say i set up both options of DROPZONE_UPLOAD_MULTIPLE and DROPZONE_PARALLEL_UPLOADS to handle 3 files but it still returns one file per request. 
I am downloaded flask-dropzone from pip wouldn’t that give me the latest version?

Thank you

**Comment by greyli** [comment]
Try to check the version with `pip show flask-dropzone`. It should be like this:
```
$ pip show flask-dropzone
Name: Flask-Dropzone
Version: 1.4.1  # <--
```

**Comment by greyli** [comment]
I finally figure out that it was some issue releated to Dropzone.js. When you enable parallel uploads, the upload input name will become something like `param[index_number]`. For example, I upload three file, here is the `request.files` we get eventually:
```python
ImmutableMultiDict([('param[2]', <FileStorage: u'4b83c89cf5daecd84ba4df44117a253a.jpg' ('image/jpeg')>), ('param[1]', <FileStorage: u'3fd8589b278c544dc10caaedfef218ac.jpg' ('image/jpeg')>), ('param[0]', <FileStorage: u'3b082acf752f82710b3800ec261898d4.jpg' ('image/jpeg')>)])
```
These three file's key was `param[2]`, `param[1]` and `param[0]`, that's why you can't get a list of file with the key `param` (e.g. `request.files.getlist('param')`). 

However, you can do something like this to get a list of file:
```python    
    if request.method == 'POST':
        file_list = []
        for i in range(len(request.files)):
            file_list.append(request.files.get('param[%d]' % i))
        # the file_list here is what you want
```
Besides, The configuration options should be like this:
```
...
DROPZONE_UPLOAD_MULTIPLE = True
DROPZONE_PARALLEL_UPLOADS = 3
```

I will update the README and add a full example a little later, sorry for the inconvenience.

**Comment by AnastasiaLd** [comment]
Hi thank you for your reply once again. Unfortunately this hasn't resolved my issue i continue to get the same result.

Code (config.py)
```
DROPZONE_INPUT_NAME = 'fileUploader'
DROPZONE_ALLOWED_FILE_CUSTOM = True
DROPZONE_ALLOWED_FILE_TYPE = '.csv, .xlsx, .xls'
DROPZONE_UPLOAD_MULTIPLE = True
DROPZONE_MAX_FILES = 3
DROPZONE_PARALLEL_UPLOADS = 3
DROPZONE_REDIRECT_VIEW = 'records.allrecords'
```

Code (main.py)
```
if request.method == 'POST':
    file_list = []
    for f in request.files.itervalues():
        file_list.append(f.filename)
    print file_list
```

Result on terminal
```
127.0.0.1 - - [03/Dec/2017 13:21:31] "GET / HTTP/1.1" 200 -
[u'test2.csv']
127.0.0.1 - - [03/Dec/2017 13:21:36] "POST / HTTP/1.1" 200 -
[u'test1.csv']
127.0.0.1 - - [03/Dec/2017 13:21:36] "POST / HTTP/1.1" 200 -
```

I am a beginner so i really apologise for bad basic code knowledge but it seems i can't find a way to make the files upload in one POST request, if i am receiving a file per request then my if statement continues to validate. What i would ideally want is to be able to retrive my files to later use concatenate them all together in one pandas dataframe. I don't know how to do this without having to save the uploaded files somewhere.

I also checked flask-dropzone version and it is the latest one, however it still won't redirect to a new view either.

Thank you for the help and for updating your documentation.

**Comment by greyli** [comment]
I can't reproduce your problem, maybe you can try the example application in [here](https://github.com/greyli/flask-dropzone/tree/master/examples).

**Comment by AnastasiaLd** [comment]
Hi! Thank you for all your help. It does indeed work, i just had to re
activate my virtual environment.

Thank you for the explanation and for updating the documentation! :)

2017-12-03 13:56 GMT+00:00 Grey Li <notifications@github.com>:

**Comment by greyli** [comment]
My pleasure! :)
