### ISSUE TITLE
how can choose the id of my dropzone or have more than one in one page

### ISSUE THREAD

**Issue by celtic34fr** [greyli/flask-dropzone#30]
Hi,
I would like to be able to fully use your extension, but I notice some limitations.
First, I can not choose the name of my dropzone, it is blocked at 'myDropzone'.

Secondly, which stems from the first rema, I can not have more than one dropzone per page which is a bit limiting.

Would it be possible to add the parameter id to dropzone.create () in order to fix a particular dropzone, knowing that if nothing is specified, 'myDropzone' will be used?

Regarding differentiate setting, I think this does not happen to be done. This can be done by limiting its python level setting to use the dropzone.config () view helper with the custom_init and custom_options parameters to do so.

Thank you for taking the time to read me, waiting for your answer.

Regards,

Celtic34fr
Béziers, Occitanie, France

**Comment by jeffreymonaco** [comment]
Hi,

Really enjoy flask-dropzone. Many thanks for making this extension available.

I wanted to inquire about the status of this particular enhancement. I have a use-case for two dropzones on a single page; the two dropzones are to distinguish between the roles of the files in an analysis method.

**Comment by greyli** [comment]
I will try to add this feature and make a new release next week.

**Comment by greyli** [comment]
Implemented and released 1.6.0. Give it a try, any feedback will be helpful. Thank you!

**Comment by jeffreymonaco** [comment]
Thanks so much for the quick turnaround on this feature. A quick scan of the code changes and the example suggest this is exactly what is needed for my use case. I will try to work this update into my app in the near term.  Thanks again.
