### ISSUE TITLE
mobile ui submits form on file select

### ISSUE THREAD

**Issue by sam2332** [greyli/flask-dropzone#34]
when used mobility this system submits the form it is attached to after it finishes loading the previews for the files.

**Comment by greyli** [comment]
Please provide a [MVCE](https://stackoverflow.com/help/minimal-reproducible-example) example that can reproduce your issue.

**Comment by sam2332** [comment]
Yeah I realize now that I forgot to leave any big report info.

I'll try to get you some on Monday.

**Comment by greyli** [comment]
Closing it now for inactive. Please feel free to reopen or comment.
