### ISSUE TITLE
dropzone.config(in_form=False) is ignored

### ISSUE THREAD

**Issue by casahome2000** [greyli/flask-dropzone#35]
I have my flask application initializing the following (`DROPZONE_IN_FORM=True`)
![image](https://user-images.githubusercontent.com/7142475/79934330-e63b9480-8417-11ea-9acb-cfefcad8e8dc.png)

When I serve an HTML page with a dropzone within a `<form>` this works, as expected.
When I serve a different HTML page that does not have a dropzone in `<form>` i'm unable to override the config by passing the custom parameter to `dropzone.config(in_form=False)`

Would like to be able to override this parameter based on how the component is used on the HTML page.

Similar to this closed issue (just an extension to handle the updated `DROPZONE_IN_FORM` config setting through the `dropzone.config()` as part of the HTML page 
https://github.com/greyli/flask-dropzone/issues/16

**Comment by greyli** [comment]
Please provide a [MVCE](https://stackoverflow.com/help/minimal-reproducible-example) example. Also, please use plain text instead of image for code snippet.

**Comment by greyli** [comment]
Closing it now for inactive. Please feel free to reopen or comment.
