### ISSUE TITLE
Proper way to use dynamic custom config.

### ISSUE THREAD

**Issue by asn1k** [greyli/flask-dropzone#37]
I want to use some custom init in dropzone. I can only come up with only one bad way.
Since Jinja doesn't support statements (if, for) in `{{ dropzone.config(custom_init = '') }}` because it's a variable, I have to put up some js code using python in Flask view functions.
Any better way?

**Comment by greyli** [comment]
Actually, you can set the variable before pass it to `custom_init` in Jinja with `{% set %}`. What's your JS code look like?

**Comment by asn1k** [comment]
Ah I see.
It's some js preloading images already stored on server, when editing images for a specific item.

btw I'm starting to use Flask based on your book.
Keep up the great works. It's a good book for beginners.
