### ISSUE TITLE
Adding custom options to support chunking upload

### ISSUE THREAD

**Issue by Gresliebear** [greyli/flask-dropzone#39]
We are trying to implement chunking in our applications but it requires custom options for drop.zone.config. 

Would you be interested in adding chunking? or point us in the right direction to improve the flask-dropzone to be more complex. 

What is the limitation

**Comment by greyli** [comment]
For complex scenarios, I will recommend just use Dropzone.js directly without this extension, check out [this tutorial](https://codecalamity.com/uploading-large-files-by-chunking-featuring-python-flask-and-dropzone-js/) for chunking upload with Flask and Dropzone.js.

**Comment by Gresliebear** [comment]
We prefer config file in python that's why I and my buddy are deciding whether or not to fork the code but we were wondering how you write a class, for instance, to add new custom options. We are looking to add classes to your repo or to fork, but we have to read all files and start testing it. 

we were asking if you could tell us how to do it faster, or if it's impossible?

**Comment by greyli** [comment]
If you just want to store the config value in Python, maybe put it in a dict, then assemble it like this:

```py
import json

config = {'chunking': True, 'forceChunking': True, 'chunkSize': 1000000}
config_string = str(json.dumps(config )).replace('"', '')[1:-1]  # pass this to custom_options
```

**Comment by Gresliebear** [comment]
Thank you we will do this, and get back to you

**Comment by greyli** [comment]
Closing it now for inactive. Please feel free to reopen or comment.
