### ISSUE TITLE
{{ dropzone.create(action_view='upload_view') }}

### ISSUE THREAD

**Issue by chiayunina** [greyli/flask-dropzone#4]
I tried

`{{ dropzone.create(action_view='upload_view') }}`

just as how README described but an error happened then. When I change to

`{{ dropzone.create(action_view='upload') }}`

, all is fine.

Guess a typo there?

**Comment by greyli** [comment]
It's just a demo value. You will need to change the `upload_view` to your actual view's endpoint (the name of view function) that handles the uploads.
