### ISSUE TITLE
Feature Request : Add a DROPZONE_MIN_FILES

### ISSUE THREAD

**Issue by itsDrac** [greyli/flask-dropzone#45]
HI there, i am making a blog app where user must submit at-least one image for post

kinda like `required` attribute in `input` tag (in html)

so i thought if there is `DROPZONE_MAX_FILES` in config
Why not `DROPZONE_MIN_FILES` 

What do you think about this?

**Comment by greyli** [comment]
Hi, sorry for the late response. The `DROPZONE_MAX_FILES` config matches the `maxFiles` in Dropzonejs, while there isn't a `minFiles` config in Dropzonejs. You could make a feature request in [Dropzonejs](https://github.com/dropzone/dropzone). These [related issues](https://github.com/dropzone/dropzone/issues?q=is%3Aissue+minimum+is%3Aclosed+) may helpful.
