### ISSUE TITLE
CSRF token missing

### ISSUE THREAD

**Issue by pykong** [greyli/flask-dropzone#6]
The generated form should conditionally contain the following:
```html
input(type='hidden', name='csrf_token', value='{{ csrf_token() }}')
```

**Comment by greyli** [comment]
Where is the `csrf_token()` come from?

**Comment by pykong** [comment]
I am still researching how to reliable retrieve the token.
Ideally we could pass ` {{ form.csrf_token }}` and let the templating engine take care of that.
So far I have not been successful with either retrieving the csrf token from `config` or `session` nor getting the above stated tag rendered.

Some starting points can be found in the docs:
https://flask-wtf.readthedocs.io/en/stable/csrf.html

**Comment by pykong** [comment]
You may also want to consider basing `flask-dropzone` on the FileUpload class provide by wtf:
https://flask-wtf.readthedocs.io/en/stable/form.html#module-flask_wtf.file

**Comment by greyli** [comment]
Since Dropzone.js use AJAX to send file, we should add the token in the X-CSRFToken header: 
```html
<script type="text/javascript">
    var csrf_token = "{{ csrf_token() }}";

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrf_token);
            }
        }
    });
</script>
```
The `csrf_token()` global was provided by [CSRFProtect extension](http://flask-wtf.readthedocs.io/en/latest/csrf.html).

**Comment by greyli** [comment]
Maybe we should let user to implement the CSRF protect, then we just need to provide an example.

**Comment by greyli** [comment]
> You may also want to consider basing flask-dropzone on the FileUpload class provide by wtf.

It seems we can't get much benefit from such integration.

**Comment by TheZoc** [comment]
I found this, on [Dropzone tips](http://www.dropzonejs.com/#tips):

>Dropzone will submit any hidden fields you have in your dropzone form. So this is an easy way to submit additional data. You can also use the params option.

**Comment by greyli** [comment]
@pykong @TheZoc Guys, this feature was added in [here](https://github.com/greyli/flask-dropzone/blob/master/flask_dropzone.py#L110-L122), thanks for your help!

**Comment by greyli** [comment]
Please review the code :)

**Comment by TheZoc** [comment]
@greyli I couldn't test it yet, but looking at the code, I have a couple questions:
- Did you include a requirement of CSRFProtect somewhere else?
- Why are the Flask.WTF and CSRFProtect checks commented out?

Other than that, the code looks great :D

**Comment by greyli** [comment]
@TheZoc 
> Did you include a requirement of CSRFProtect somewhere else?

IMO, the CSRF feature is additional, and in default it was disabled. We just add support to use with CSRFProtect, but it's not a dependency actually. So maybe it's better to let user to install it manually. 

> Why are the Flask.WTF and CSRFProtect checks commented out?

Because I currently not sure what's the best way to handle the check. Maybe we should only keep the Flask-WTF check.

**Comment by pykong** [comment]
@greyli Sorry, missed your call. Thanks for implementing.
Code looks good to me.

**Comment by greyli** [comment]
@pykong @TheZoc I finally keep [the check for `CSRFProtect`](https://github.com/greyli/flask-dropzone/blob/master/flask_dropzone.py#L125) and *make the error message more descriptive* :), thanks!

**Comment by TheZoc** [comment]
Looks good to me! :)
